package com.zhaw.hhapp.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Model class representing a single expense entry.
 * <p>
 * Each Expense contains an amount, description, date, and user name.
 * Provides methods for CSV serialization and deserialization.
 * </p>
 */
@Entity
public class Expense {


    /** The amount of the expense. */
    private double amount;

    /** The description of the expense (e.g., what was bought). */
    private String description;

    /** The date of the expense, formatted as dd.MM.yyyy. */
    private String date;

    /** The username of the person who created the expense. */
    private String userName;

    /**
     * The unique ID of the expense, automatically generated by the database
     * when a new record is inserted.
     *
     * Uses GenerationType.IDENTITY to let the database assign a unique,
     * auto-incremented value. No manual ID setting is needed.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Constructs a new Expense object.
     * If date is empty, the current date is used.
     * If userName is empty, the system username is used.
     *
     * @param amount      The amount of the expense.
     * @param description The description of the expense.
     * @param date        The date of the expense (format: dd.MM.yyyy), or empty for today.
     * @param userName    The name of the user, or empty for system username.
     */
    public Expense(double amount, String description, String date, String userName) {
        this.amount = amount;
        this.description = description;
        if (userName.length() > 0) {
            this.userName = userName;
        } else {
            this.userName = System.getProperty("user.name");
        }
        if (date.length() > 0) {

            this.date = date;
        } else {
            this.date = LocalDate.now().format(DateTimeFormatter.ofPattern("dd.MM.yyyy"));
        }
    }

    public Expense() {

    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
    /**
     * Returns the amount of the expense.
     *
     * @return The amount as double.
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Returns the description of the expense.
     *
     * @return The description as String.
     */
    public String getDescription() {
        return description;
    }

    /**
     * Returns the username who created the expense.
     *
     * @return The username as String.
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Returns the date of the expense (format: dd.MM.yyyy).
     *
     * @return The date as String.
     */
    public String getDate() {
        return date;
    }

    /**
     * Returns a comma-separated String representation of the expense.
     *
     * @return Comma-separated expense data.
     */
    @Override
    public String toString() {
        return String.format("%.2f,%s,%s,%s", amount, description, date, userName);
    }

    /**
     * Returns a pipe-separated CSV String of the expense for file export.
     *
     * @return Pipe-separated CSV string.
     */
    public String toCsvString() {
        return String.format("%.2f|%s|%s|%s", amount, description, date, userName);
    }

    /**
     * Creates an Expense object from a CSV string.
     * The expected format is: amount|description|date|userName
     *
     * @param line The CSV line to parse.
     * @return An Expense object.
     * @throws IllegalArgumentException If the format is invalid.
     */
    public static Expense fromCsvString(String line) {
        String[] parts = line.split("\\|", 4); // Das Pipe-Zeichen muss als Regex escaped werden
        if (parts.length != 4) {
            throw new IllegalArgumentException("Invalid CSV format for Expense: " + line);
        }
        double amount = Double.parseDouble(parts[0]);
        String description = parts[1];
        String date = parts[2];
        String userName = parts[3];
        return new Expense(amount, description, date, userName);
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }
}
